apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    app.kubernetes.io/component: minio
  name: minio
spec:
  ports:
  - name: minio
    port: 9000
    targetPort: minio
  selector:
    app: minio
  type: ClusterIP
